max_width = 150
chain_width = 100
fn_call_width = 150
hard_tabs = true
fn_args_layout = "Compressed"
use_small_heuristics = "Max"
use_field_init_shorthand = true
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
tab_spaces = 2
struct_lit_width = 100
