// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use diesel::{prelude::Insertable, Queryable};
use serde::{Deserialize, Serialize};
#[derive(Queryable, Debug, Serialize, Deserialize)]
pub struct Book {
    pub id: i32,
    pub title: String,
    pub author: String,
    pub publication: Option<String>,
    pub year: Option<i32>,
}
